// CmdLineExt.idl : IDL source for CmdLineExt
//

// This file will be processed by the MIDL tool to
// produce the type library (CmdLineExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(FC8BECFA-13D1-47F7-AC79-22EBFB5F3DFD),
	version(1.0),
	helpstring("DFTContextMenuHandler 1.0 Type Library")
]
library CmdLineExtLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F062AE83-FCD6-4845-BA4E-D74FC5D59B38),
		helpstring("DFTContextMenu Class")
	]
	coclass CmdLineContextMenu
	{
		[default] interface IUnknown;
	};
};

